In [1]:
import numpy as np 
import pandas as pd


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/playground-series-s4e4/sample_submission.csv
/kaggle/input/playground-series-s4e4/train.csv
/kaggle/input/playground-series-s4e4/test.csv


In [2]:
traindata=pd.read_csv("/kaggle/input/playground-series-s4e4/train.csv")
testdata=pd.read_csv("/kaggle/input/playground-series-s4e4/test.csv")
subdata=pd.read_csv("/kaggle/input/playground-series-s4e4/sample_submission.csv")

In [3]:
traindata

id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0          0   F   0.550     0.430   0.150        0.7715          0.3285   
1          1   F   0.630     0.490   0.145        1.1300          0.4580   
2          2   I   0.160     0.110   0.025        0.0210          0.0055   
3          3   M   0.595     0.475   0.150        0.9145          0.3755   
4          4   I   0.555     0.425   0.130        0.7820          0.3695   
...      ...  ..     ...       ...     ...           ...             ...   
90610  90610   M   0.335     0.235   0.075        0.1585          0.0685   
90611  90611   M   0.555     0.425   0.150        0.8790          0.3865   
90612  90612   I   0.435     0.330   0.095        0.3215          0.1510   
90613  90613   I   0.345     0.270   0.075        0.2000          0.0980   
90614  90614   I   0.425     0.325   0.100        0.3455          0.1525   

       Whole weight.2  Shell weight  Rings  
0              0.1465        0.2400     11  
1              0.2765        0.3200     11  
2              0.0030        0.0050      6  
3              0.2055        0.2500     10  
4              0.1600        0.1975      9  
...               ...           ...    ...  
90610          0.0370        0.0450      6  
90611          0.1815        0.2400      9  
90612          0.0785        0.0815      6  
90613          0.0490        0.0700      6  
90614          0.0785        0.1050      8  

[90615 rows x 10 columns]

In [4]:
testdata

id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0       90615   M   0.645     0.475   0.155        1.2380          0.6185   
1       90616   M   0.580     0.460   0.160        0.9830          0.4785   
2       90617   M   0.560     0.420   0.140        0.8395          0.3525   
3       90618   M   0.570     0.490   0.145        0.8740          0.3525   
4       90619   I   0.415     0.325   0.110        0.3580          0.1575   
...       ...  ..     ...       ...     ...           ...             ...   
60406  151021   I   0.345     0.260   0.085        0.1775          0.0735   
60407  151022   F   0.525     0.410   0.145        0.8445          0.3885   
60408  151023   I   0.590     0.440   0.155        1.1220          0.3930   
60409  151024   F   0.660     0.525   0.190        1.4935          0.5885   
60410  151025   F   0.430     0.340   0.120        0.4150          0.1525   

       Whole weight.2  Shell weight  
0              0.3125        0.3005  
1              0.2195        0.2750  
2              0.1845        0.2405  
3              0.1865        0.2350  
4              0.0670        0.1050  
...               ...           ...  
60406          0.0265        0.0500  
60407          0.1670        0.2050  
60408          0.2000        0.2650  
60409          0.3575        0.4350  
60410          0.0910        0.0905  

[60411 rows x 9 columns]

In [5]:
subdata

id  Rings
0       90615     10
1       90616     10
2       90617     10
3       90618     10
4       90619     10
...       ...    ...
60406  151021     10
60407  151022     10
60408  151023     10
60409  151024     10
60410  151025     10

[60411 rows x 2 columns]

In [6]:
traindata.isnull().sum()

id                0
Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Whole weight.1    0
Whole weight.2    0
Shell weight      0
Rings             0
dtype: int64

In [7]:
traindata.shape

(90615, 10)

In [8]:
traindata.describe()

id        Length      Diameter        Height  Whole weight  \
count  90615.000000  90615.000000  90615.000000  90615.000000  90615.000000   
mean   45307.000000      0.517098      0.401679      0.135464      0.789035   
std    26158.441658      0.118217      0.098026      0.038008      0.457671   
min        0.000000      0.075000      0.055000      0.000000      0.002000   
25%    22653.500000      0.445000      0.345000      0.110000      0.419000   
50%    45307.000000      0.545000      0.425000      0.140000      0.799500   
75%    67960.500000      0.600000      0.470000      0.160000      1.067500   
max    90614.000000      0.815000      0.650000      1.130000      2.825500   

       Whole weight.1  Whole weight.2  Shell weight         Rings  
count    90615.000000    90615.000000  90615.000000  90615.000000  
mean         0.340778        0.169422      0.225898      9.696794  
std          0.204428        0.100909      0.130203      3.176221  
min          0.001000        0.000500      0.001500      1.000000  
25%          0.177500        0.086500      0.120000      8.000000  
50%          0.330000        0.166000      0.225000      9.000000  
75%          0.463000        0.232500      0.305000     11.000000  
max          1.488000        0.760000      1.005000     29.000000

In [9]:
ytrain=traindata["Rings"]

In [10]:
ytrain

0        11
1        11
2         6
3        10
4         9
         ..
90610     6
90611     9
90612     6
90613     6
90614     8
Name: Rings, Length: 90615, dtype: int64

In [11]:
xtrain=traindata.drop("Rings", axis=1)

In [12]:
xtrain

id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0          0   F   0.550     0.430   0.150        0.7715          0.3285   
1          1   F   0.630     0.490   0.145        1.1300          0.4580   
2          2   I   0.160     0.110   0.025        0.0210          0.0055   
3          3   M   0.595     0.475   0.150        0.9145          0.3755   
4          4   I   0.555     0.425   0.130        0.7820          0.3695   
...      ...  ..     ...       ...     ...           ...             ...   
90610  90610   M   0.335     0.235   0.075        0.1585          0.0685   
90611  90611   M   0.555     0.425   0.150        0.8790          0.3865   
90612  90612   I   0.435     0.330   0.095        0.3215          0.1510   
90613  90613   I   0.345     0.270   0.075        0.2000          0.0980   
90614  90614   I   0.425     0.325   0.100        0.3455          0.1525   

       Whole weight.2  Shell weight  
0              0.1465        0.2400  
1              0.2765        0.3200  
2              0.0030        0.0050  
3              0.2055        0.2500  
4              0.1600        0.1975  
...               ...           ...  
90610          0.0370        0.0450  
90611          0.1815        0.2400  
90612          0.0785        0.0815  
90613          0.0490        0.0700  
90614          0.0785        0.1050  

[90615 rows x 9 columns]

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_log_error
from sklearn.ensemble import RandomForestRegressor

In [14]:
xtrain, xval, ytrain, yval = train_test_split(xtrain, ytrain, test_size=0.2, random_state=42)

In [15]:
xtrain

id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
43718  43718   M   0.650     0.505   0.175        1.3850          0.7105   
45247  45247   F   0.670     0.520   0.195        1.5405          0.6370   
71393  71393   M   0.605     0.495   0.150        1.1345          0.5585   
51688  51688   M   0.680     0.560   0.200        1.5340          0.6900   
40681  40681   I   0.295     0.200   0.075        0.1075          0.0350   
...      ...  ..     ...       ...     ...           ...             ...   
6265    6265   I   0.350     0.265   0.080        0.1790          0.0630   
54886  54886   F   0.580     0.460   0.140        0.8435          0.3365   
76820  76820   I   0.530     0.420   0.125        0.5965          0.2505   
860      860   M   0.695     0.525   0.185        1.8275          0.8850   
15795  15795   I   0.370     0.275   0.095        0.2225          0.0960   

       Whole weight.2  Shell weight  
43718          0.3020         0.360  
45247          0.3455         0.385  
71393          0.2470         0.285  
51688          0.3060         0.440  
40681          0.0190         0.038  
...               ...           ...  
6265           0.0380         0.055  
54886          0.1665         0.225  
76820          0.1435         0.170  
860            0.4095         0.499  
15795          0.0455         0.080  

[72492 rows x 9 columns]

In [16]:
xval

id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
3502    3502   I   0.490     0.380   0.125        0.5290          0.2165   
76031  76031   I   0.420     0.345   0.100        0.3705          0.1625   
49473  49473   M   0.555     0.440   0.135        0.7390          0.3515   
16126  16126   F   0.535     0.410   0.140        0.7090          0.2505   
65405  65405   F   0.605     0.455   0.150        1.0590          0.4275   
...      ...  ..     ...       ...     ...           ...             ...   
71483  71483   M   0.575     0.415   0.125        0.8020          0.3495   
76423  76423   M   0.590     0.435   0.135        0.9745          0.4445   
67841  67841   F   0.450     0.350   0.115        0.4960          0.1905   
36518  36518   M   0.670     0.505   0.175        1.3080          0.5425   
79416  79416   M   0.600     0.470   0.175        1.0350          0.4375   

       Whole weight.2  Shell weight  
3502           0.1375        0.1550  
76031          0.0795        0.1025  
49473          0.1575        0.2350  
16126          0.1700        0.1900  
65405          0.2210        0.3100  
...               ...           ...  
71483          0.1655        0.2405  
76423          0.2525        0.2715  
67841          0.1245        0.1550  
36518          0.3230        0.3745  
79416          0.2680        0.2850  

[18123 rows x 9 columns]

In [17]:
ytrain.shape

(72492,)

In [18]:
yval.shape

(18123,)

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
xtrain=pd.get_dummies(xtrain)
xval=pd.get_dummies(xval)

In [21]:
model = LinearRegression()
model=model.fit(xtrain, ytrain)

In [22]:
model

LinearRegression()

In [23]:
ypred=model.predict(xval)

In [24]:
ypred

array([ 8.67135522,  7.5342094 , 10.0848556 , ...,  9.35663506,
       12.09349257, 11.05659314])

In [25]:
ypred = np.maximum(ypred, 0) #to ensure that ypred is non-negative value

In [26]:
ypred

array([ 8.67135522,  7.5342094 , 10.0848556 , ...,  9.35663506,
       12.09349257, 11.05659314])

In [27]:
from sklearn.metrics import mean_squared_log_error
rmsle = mean_squared_log_error(ypred,yval) ** 0.5
print("RMSLE:", rmsle)

RMSLE: 0.16678492724005445


In [28]:
testdata

id Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
0       90615   M   0.645     0.475   0.155        1.2380          0.6185   
1       90616   M   0.580     0.460   0.160        0.9830          0.4785   
2       90617   M   0.560     0.420   0.140        0.8395          0.3525   
3       90618   M   0.570     0.490   0.145        0.8740          0.3525   
4       90619   I   0.415     0.325   0.110        0.3580          0.1575   
...       ...  ..     ...       ...     ...           ...             ...   
60406  151021   I   0.345     0.260   0.085        0.1775          0.0735   
60407  151022   F   0.525     0.410   0.145        0.8445          0.3885   
60408  151023   I   0.590     0.440   0.155        1.1220          0.3930   
60409  151024   F   0.660     0.525   0.190        1.4935          0.5885   
60410  151025   F   0.430     0.340   0.120        0.4150          0.1525   

       Whole weight.2  Shell weight  
0              0.3125        0.3005  
1              0.2195        0.2750  
2              0.1845        0.2405  
3              0.1865        0.2350  
4              0.0670        0.1050  
...               ...           ...  
60406          0.0265        0.0500  
60407          0.1670        0.2050  
60408          0.2000        0.2650  
60409          0.3575        0.4350  
60410          0.0910        0.0905  

[60411 rows x 9 columns]

In [29]:
xtest=testdata.drop("id", axis=1)

In [30]:
xtest=pd.get_dummies(testdata)

In [31]:
xtest

id  Length  Diameter  Height  Whole weight  Whole weight.1  \
0       90615   0.645     0.475   0.155        1.2380          0.6185   
1       90616   0.580     0.460   0.160        0.9830          0.4785   
2       90617   0.560     0.420   0.140        0.8395          0.3525   
3       90618   0.570     0.490   0.145        0.8740          0.3525   
4       90619   0.415     0.325   0.110        0.3580          0.1575   
...       ...     ...       ...     ...           ...             ...   
60406  151021   0.345     0.260   0.085        0.1775          0.0735   
60407  151022   0.525     0.410   0.145        0.8445          0.3885   
60408  151023   0.590     0.440   0.155        1.1220          0.3930   
60409  151024   0.660     0.525   0.190        1.4935          0.5885   
60410  151025   0.430     0.340   0.120        0.4150          0.1525   

       Whole weight.2  Shell weight  Sex_F  Sex_I  Sex_M  
0              0.3125        0.3005  False  False   True  
1              0.2195        0.2750  False  False   True  
2              0.1845        0.2405  False  False   True  
3              0.1865        0.2350  False  False   True  
4              0.0670        0.1050  False   True  False  
...               ...           ...    ...    ...    ...  
60406          0.0265        0.0500  False   True  False  
60407          0.1670        0.2050   True  False  False  
60408          0.2000        0.2650  False   True  False  
60409          0.3575        0.4350   True  False  False  
60410          0.0910        0.0905   True  False  False  

[60411 rows x 11 columns]

In [32]:
y=model.predict(xtest)

In [33]:
y

array([ 8.52926666,  9.98983872, 10.27865116, ..., 10.76809149,
       13.5174023 ,  8.53457857])

In [34]:
test_predictions = np.maximum(y, 0)

In [35]:
test_predictions

array([ 8.52926666,  9.98983872, 10.27865116, ..., 10.76809149,
       13.5174023 ,  8.53457857])

In [36]:
submission = pd.DataFrame({"id": testdata["id"], "Rings": test_predictions})
submission.to_csv("submission.csv", index=False)